// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 *
 *
 * @schema GitRepository
 */
export class GitRepository extends ApiObject {
  /**
   * Returns the apiVersion and kind for "GitRepository"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'idpbuilder.cnoe.io/v1alpha1',
    kind: 'GitRepository',
  }

  /**
   * Renders a Kubernetes manifest for "GitRepository".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: GitRepositoryProps = {}): any {
    return {
      ...GitRepository.GVK,
      ...toJson_GitRepositoryProps(props),
    };
  }

  /**
   * Defines a "GitRepository" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: GitRepositoryProps = {}) {
    super(scope, id, {
      ...GitRepository.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public toJson(): any {
    const resolved = super.toJson();

    return {
      ...GitRepository.GVK,
      ...toJson_GitRepositoryProps(resolved),
    };
  }
}

/**
 * @schema GitRepository
 */
export interface GitRepositoryProps {
  /**
   * @schema GitRepository#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * @schema GitRepository#spec
   */
  readonly spec?: GitRepositorySpec;

}

/**
 * Converts an object of type 'GitRepositoryProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositoryProps(obj: GitRepositoryProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_GitRepositorySpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GitRepositorySpec
 */
export interface GitRepositorySpec {
  /**
   * PackageCustomization defines how packages are customized
   *
   * @schema GitRepositorySpec#customization
   */
  readonly customization?: GitRepositorySpecCustomization;

  /**
   * @schema GitRepositorySpec#provider
   */
  readonly provider: GitRepositorySpecProvider;

  /**
   * SecretRef is the reference to secret that contain Git server credentials
   *
   * @schema GitRepositorySpec#secretRef
   */
  readonly secretRef?: GitRepositorySpecSecretRef;

  /**
   * @schema GitRepositorySpec#source
   */
  readonly source?: GitRepositorySpecSource;

}

/**
 * Converts an object of type 'GitRepositorySpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpec(obj: GitRepositorySpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'customization': toJson_GitRepositorySpecCustomization(obj.customization),
    'provider': toJson_GitRepositorySpecProvider(obj.provider),
    'secretRef': toJson_GitRepositorySpecSecretRef(obj.secretRef),
    'source': toJson_GitRepositorySpecSource(obj.source),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * PackageCustomization defines how packages are customized
 *
 * @schema GitRepositorySpecCustomization
 */
export interface GitRepositorySpecCustomization {
  /**
   * FilePath is the absolute file path to a YAML file that contains Kubernetes manifests.
   *
   * @schema GitRepositorySpecCustomization#filePath
   */
  readonly filePath?: string;

  /**
   * Name is the name of the package to be customized. e.g. argocd
   *
   * @schema GitRepositorySpecCustomization#name
   */
  readonly name: string;

}

/**
 * Converts an object of type 'GitRepositorySpecCustomization' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpecCustomization(obj: GitRepositorySpecCustomization | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'filePath': obj.filePath,
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GitRepositorySpecProvider
 */
export interface GitRepositorySpecProvider {
  /**
   * GitURL is the base URL of Git server used for API calls.
   *
   * @schema GitRepositorySpecProvider#gitURL
   */
  readonly gitUrl: string;

  /**
   * InternalGitURL is the base URL of Git server accessible within the cluster only.
   *
   * @schema GitRepositorySpecProvider#internalGitURL
   */
  readonly internalGitUrl: string;

  /**
   * @schema GitRepositorySpecProvider#name
   */
  readonly name: GitRepositorySpecProviderName;

  /**
   * @schema GitRepositorySpecProvider#organizationName
   */
  readonly organizationName: string;

}

/**
 * Converts an object of type 'GitRepositorySpecProvider' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpecProvider(obj: GitRepositorySpecProvider | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'gitURL': obj.gitUrl,
    'internalGitURL': obj.internalGitUrl,
    'name': obj.name,
    'organizationName': obj.organizationName,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * SecretRef is the reference to secret that contain Git server credentials
 *
 * @schema GitRepositorySpecSecretRef
 */
export interface GitRepositorySpecSecretRef {
  /**
   * @schema GitRepositorySpecSecretRef#name
   */
  readonly name: string;

  /**
   * @schema GitRepositorySpecSecretRef#namespace
   */
  readonly namespace: string;

}

/**
 * Converts an object of type 'GitRepositorySpecSecretRef' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpecSecretRef(obj: GitRepositorySpecSecretRef | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'name': obj.name,
    'namespace': obj.namespace,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GitRepositorySpecSource
 */
export interface GitRepositorySpecSource {
  /**
   * @schema GitRepositorySpecSource#embeddedAppName
   */
  readonly embeddedAppName?: GitRepositorySpecSourceEmbeddedAppName;

  /**
   * Path is the absolute path to directory that contains Kustomize structure or raw manifests.
   * This is required when Type is set to local.
   *
   * @schema GitRepositorySpecSource#path
   */
  readonly path?: string;

  /**
   * RemoteRepositorySpec specifies information about remote repositories.
   *
   * @schema GitRepositorySpecSource#remoteRepository
   */
  readonly remoteRepository: GitRepositorySpecSourceRemoteRepository;

  /**
   * Type is the source type.
   *
   * @schema GitRepositorySpecSource#type
   */
  readonly type: GitRepositorySpecSourceType;

}

/**
 * Converts an object of type 'GitRepositorySpecSource' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpecSource(obj: GitRepositorySpecSource | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'embeddedAppName': obj.embeddedAppName,
    'path': obj.path,
    'remoteRepository': toJson_GitRepositorySpecSourceRemoteRepository(obj.remoteRepository),
    'type': obj.type,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema GitRepositorySpecProviderName
 */
export enum GitRepositorySpecProviderName {
  /** gitea */
  GITEA = "gitea",
  /** github */
  GITHUB = "github",
}

/**
 * @schema GitRepositorySpecSourceEmbeddedAppName
 */
export enum GitRepositorySpecSourceEmbeddedAppName {
  /** argocd */
  ARGOCD = "argocd",
  /** gitea */
  GITEA = "gitea",
  /** nginx */
  NGINX = "nginx",
}

/**
 * RemoteRepositorySpec specifies information about remote repositories.
 *
 * @schema GitRepositorySpecSourceRemoteRepository
 */
export interface GitRepositorySpecSourceRemoteRepository {
  /**
   * @schema GitRepositorySpecSourceRemoteRepository#cloneSubmodules
   */
  readonly cloneSubmodules: boolean;

  /**
   * @schema GitRepositorySpecSourceRemoteRepository#path
   */
  readonly path: string;

  /**
   * Ref specifies the specific ref supported by git fetch
   *
   * @schema GitRepositorySpecSourceRemoteRepository#ref
   */
  readonly ref: string;

  /**
   * Url specifies the url to the repository containing the ArgoCD application file
   *
   * @schema GitRepositorySpecSourceRemoteRepository#url
   */
  readonly url: string;

}

/**
 * Converts an object of type 'GitRepositorySpecSourceRemoteRepository' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_GitRepositorySpecSourceRemoteRepository(obj: GitRepositorySpecSourceRemoteRepository | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'cloneSubmodules': obj.cloneSubmodules,
    'path': obj.path,
    'ref': obj.ref,
    'url': obj.url,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Type is the source type.
 *
 * @schema GitRepositorySpecSourceType
 */
export enum GitRepositorySpecSourceType {
  /** local */
  LOCAL = "local",
  /** embedded */
  EMBEDDED = "embedded",
  /** remote */
  REMOTE = "remote",
}

