// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface ExternalsecretsProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: ExternalsecretsValues;
}

export class Externalsecrets extends Construct {
  public constructor(scope: Construct, id: string, props: ExternalsecretsProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const { additionalValues, ...valuesWithoutAdditionalValues } = props.values;
      updatedProps = {
        ...props,
        values: {
          ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
          ...additionalValues,
        },
      };
    }

    const finalProps: HelmProps = {
      chart: 'external-secrets',
      repo: 'https://charts.external-secrets.io',
      version: '0.18.2',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema external-secrets
 */
export interface ExternalsecretsValues {
  /**
   * @schema external-secrets#affinity
   */
  readonly affinity?: ExternalSecretsAffinity;

  /**
   * @schema external-secrets#bitwarden-sdk-server
   */
  readonly bitwardenSdkServer?: { [key: string]: any };

  /**
   * @schema external-secrets#certController
   */
  readonly certController?: ExternalSecretsCertController;

  /**
   * @schema external-secrets#commonLabels
   */
  readonly commonLabels?: ExternalSecretsCommonLabels;

  /**
   * @schema external-secrets#concurrent
   */
  readonly concurrent?: number;

  /**
   * @schema external-secrets#controllerClass
   */
  readonly controllerClass?: string;

  /**
   * @schema external-secrets#crds
   */
  readonly crds?: ExternalSecretsCrds;

  /**
   * @schema external-secrets#createOperator
   */
  readonly createOperator?: boolean;

  /**
   * @schema external-secrets#deploymentAnnotations
   */
  readonly deploymentAnnotations?: ExternalSecretsDeploymentAnnotations;

  /**
   * @schema external-secrets#dnsConfig
   */
  readonly dnsConfig?: ExternalSecretsDnsConfig;

  /**
   * @schema external-secrets#dnsPolicy
   */
  readonly dnsPolicy?: string;

  /**
   * @schema external-secrets#extendedMetricLabels
   */
  readonly extendedMetricLabels?: boolean;

  /**
   * @schema external-secrets#extraArgs
   */
  readonly extraArgs?: ExternalSecretsExtraArgs;

  /**
   * @schema external-secrets#extraContainers
   */
  readonly extraContainers?: any[];

  /**
   * @schema external-secrets#extraEnv
   */
  readonly extraEnv?: any[];

  /**
   * @schema external-secrets#extraObjects
   */
  readonly extraObjects?: any[];

  /**
   * @schema external-secrets#extraVolumeMounts
   */
  readonly extraVolumeMounts?: any[];

  /**
   * @schema external-secrets#extraVolumes
   */
  readonly extraVolumes?: any[];

  /**
   * @schema external-secrets#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema external-secrets#global
   */
  readonly global?: { [key: string]: any };

  /**
   * @schema external-secrets#grafanaDashboard
   */
  readonly grafanaDashboard?: ExternalSecretsGrafanaDashboard;

  /**
   * @schema external-secrets#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema external-secrets#image
   */
  readonly image?: ExternalSecretsImage;

  /**
   * @schema external-secrets#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema external-secrets#installCRDs
   */
  readonly installCrDs?: boolean;

  /**
   * @schema external-secrets#leaderElect
   */
  readonly leaderElect?: boolean;

  /**
   * @schema external-secrets#log
   */
  readonly log?: ExternalSecretsLog;

  /**
   * @schema external-secrets#metrics
   */
  readonly metrics?: ExternalSecretsMetrics;

  /**
   * @schema external-secrets#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema external-secrets#namespaceOverride
   */
  readonly namespaceOverride?: string;

  /**
   * @schema external-secrets#nodeSelector
   */
  readonly nodeSelector?: ExternalSecretsNodeSelector;

  /**
   * @schema external-secrets#openshiftFinalizers
   */
  readonly openshiftFinalizers?: boolean;

  /**
   * @schema external-secrets#podAnnotations
   */
  readonly podAnnotations?: ExternalSecretsPodAnnotations;

  /**
   * @schema external-secrets#podDisruptionBudget
   */
  readonly podDisruptionBudget?: ExternalSecretsPodDisruptionBudget;

  /**
   * @schema external-secrets#podLabels
   */
  readonly podLabels?: ExternalSecretsPodLabels;

  /**
   * @schema external-secrets#podSecurityContext
   */
  readonly podSecurityContext?: ExternalSecretsPodSecurityContext;

  /**
   * @schema external-secrets#podSpecExtra
   */
  readonly podSpecExtra?: ExternalSecretsPodSpecExtra;

  /**
   * @schema external-secrets#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema external-secrets#processClusterExternalSecret
   */
  readonly processClusterExternalSecret?: boolean;

  /**
   * @schema external-secrets#processClusterPushSecret
   */
  readonly processClusterPushSecret?: boolean;

  /**
   * @schema external-secrets#processClusterStore
   */
  readonly processClusterStore?: boolean;

  /**
   * @schema external-secrets#processPushSecret
   */
  readonly processPushSecret?: boolean;

  /**
   * @schema external-secrets#rbac
   */
  readonly rbac?: ExternalSecretsRbac;

  /**
   * @schema external-secrets#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema external-secrets#resources
   */
  readonly resources?: ExternalSecretsResources;

  /**
   * @schema external-secrets#revisionHistoryLimit
   */
  readonly revisionHistoryLimit?: number;

  /**
   * @schema external-secrets#scopedNamespace
   */
  readonly scopedNamespace?: string;

  /**
   * @schema external-secrets#scopedRBAC
   */
  readonly scopedRbac?: boolean;

  /**
   * @schema external-secrets#securityContext
   */
  readonly securityContext?: ExternalSecretsSecurityContext;

  /**
   * @schema external-secrets#service
   */
  readonly service?: ExternalSecretsService;

  /**
   * @schema external-secrets#serviceAccount
   */
  readonly serviceAccount?: ExternalSecretsServiceAccount;

  /**
   * @schema external-secrets#serviceMonitor
   */
  readonly serviceMonitor?: ExternalSecretsServiceMonitor;

  /**
   * @schema external-secrets#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema external-secrets#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * @schema external-secrets#webhook
   */
  readonly webhook?: ExternalSecretsWebhook;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema external-secrets#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsAffinity
 */
export interface ExternalSecretsAffinity {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsAffinity#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertController
 */
export interface ExternalSecretsCertController {
  /**
   * @schema ExternalSecretsCertController#affinity
   */
  readonly affinity?: ExternalSecretsCertControllerAffinity;

  /**
   * @schema ExternalSecretsCertController#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsCertController#deploymentAnnotations
   */
  readonly deploymentAnnotations?: ExternalSecretsCertControllerDeploymentAnnotations;

  /**
   * @schema ExternalSecretsCertController#extraArgs
   */
  readonly extraArgs?: ExternalSecretsCertControllerExtraArgs;

  /**
   * @schema ExternalSecretsCertController#extraEnv
   */
  readonly extraEnv?: any[];

  /**
   * @schema ExternalSecretsCertController#extraVolumeMounts
   */
  readonly extraVolumeMounts?: any[];

  /**
   * @schema ExternalSecretsCertController#extraVolumes
   */
  readonly extraVolumes?: any[];

  /**
   * @schema ExternalSecretsCertController#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema ExternalSecretsCertController#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema ExternalSecretsCertController#image
   */
  readonly image?: ExternalSecretsCertControllerImage;

  /**
   * @schema ExternalSecretsCertController#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema ExternalSecretsCertController#log
   */
  readonly log?: ExternalSecretsCertControllerLog;

  /**
   * @schema ExternalSecretsCertController#metrics
   */
  readonly metrics?: ExternalSecretsCertControllerMetrics;

  /**
   * @schema ExternalSecretsCertController#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema ExternalSecretsCertController#nodeSelector
   */
  readonly nodeSelector?: ExternalSecretsCertControllerNodeSelector;

  /**
   * @schema ExternalSecretsCertController#podAnnotations
   */
  readonly podAnnotations?: ExternalSecretsCertControllerPodAnnotations;

  /**
   * @schema ExternalSecretsCertController#podDisruptionBudget
   */
  readonly podDisruptionBudget?: ExternalSecretsCertControllerPodDisruptionBudget;

  /**
   * @schema ExternalSecretsCertController#podLabels
   */
  readonly podLabels?: ExternalSecretsCertControllerPodLabels;

  /**
   * @schema ExternalSecretsCertController#podSecurityContext
   */
  readonly podSecurityContext?: ExternalSecretsCertControllerPodSecurityContext;

  /**
   * @schema ExternalSecretsCertController#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema ExternalSecretsCertController#rbac
   */
  readonly rbac?: ExternalSecretsCertControllerRbac;

  /**
   * @schema ExternalSecretsCertController#readinessProbe
   */
  readonly readinessProbe?: ExternalSecretsCertControllerReadinessProbe;

  /**
   * @schema ExternalSecretsCertController#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema ExternalSecretsCertController#requeueInterval
   */
  readonly requeueInterval?: string;

  /**
   * @schema ExternalSecretsCertController#resources
   */
  readonly resources?: ExternalSecretsCertControllerResources;

  /**
   * @schema ExternalSecretsCertController#revisionHistoryLimit
   */
  readonly revisionHistoryLimit?: number;

  /**
   * @schema ExternalSecretsCertController#securityContext
   */
  readonly securityContext?: ExternalSecretsCertControllerSecurityContext;

  /**
   * @schema ExternalSecretsCertController#serviceAccount
   */
  readonly serviceAccount?: ExternalSecretsCertControllerServiceAccount;

  /**
   * @schema ExternalSecretsCertController#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema ExternalSecretsCertController#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertController#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCommonLabels
 */
export interface ExternalSecretsCommonLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCommonLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCrds
 */
export interface ExternalSecretsCrds {
  /**
   * @schema ExternalSecretsCrds#annotations
   */
  readonly annotations?: ExternalSecretsCrdsAnnotations;

  /**
   * @schema ExternalSecretsCrds#conversion
   */
  readonly conversion?: ExternalSecretsCrdsConversion;

  /**
   * @schema ExternalSecretsCrds#createClusterExternalSecret
   */
  readonly createClusterExternalSecret?: boolean;

  /**
   * @schema ExternalSecretsCrds#createClusterGenerator
   */
  readonly createClusterGenerator?: boolean;

  /**
   * @schema ExternalSecretsCrds#createClusterPushSecret
   */
  readonly createClusterPushSecret?: boolean;

  /**
   * @schema ExternalSecretsCrds#createClusterSecretStore
   */
  readonly createClusterSecretStore?: boolean;

  /**
   * @schema ExternalSecretsCrds#createPushSecret
   */
  readonly createPushSecret?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCrds#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsDeploymentAnnotations
 */
export interface ExternalSecretsDeploymentAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsDeploymentAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsDnsConfig
 */
export interface ExternalSecretsDnsConfig {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsDnsConfig#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsExtraArgs
 */
export interface ExternalSecretsExtraArgs {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsExtraArgs#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsGrafanaDashboard
 */
export interface ExternalSecretsGrafanaDashboard {
  /**
   * @schema ExternalSecretsGrafanaDashboard#annotations
   */
  readonly annotations?: ExternalSecretsGrafanaDashboardAnnotations;

  /**
   * @schema ExternalSecretsGrafanaDashboard#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsGrafanaDashboard#sidecarLabel
   */
  readonly sidecarLabel?: string;

  /**
   * @schema ExternalSecretsGrafanaDashboard#sidecarLabelValue
   */
  readonly sidecarLabelValue?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsGrafanaDashboard#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsImage
 */
export interface ExternalSecretsImage {
  /**
   * @schema ExternalSecretsImage#flavour
   */
  readonly flavour?: string;

  /**
   * @schema ExternalSecretsImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema ExternalSecretsImage#repository
   */
  readonly repository?: string;

  /**
   * @schema ExternalSecretsImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsLog
 */
export interface ExternalSecretsLog {
  /**
   * @schema ExternalSecretsLog#level
   */
  readonly level?: string;

  /**
   * @schema ExternalSecretsLog#timeEncoding
   */
  readonly timeEncoding?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsLog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsMetrics
 */
export interface ExternalSecretsMetrics {
  /**
   * @schema ExternalSecretsMetrics#listen
   */
  readonly listen?: ExternalSecretsMetricsListen;

  /**
   * @schema ExternalSecretsMetrics#service
   */
  readonly service?: ExternalSecretsMetricsService;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsNodeSelector
 */
export interface ExternalSecretsNodeSelector {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsNodeSelector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsPodAnnotations
 */
export interface ExternalSecretsPodAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsPodAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsPodDisruptionBudget
 */
export interface ExternalSecretsPodDisruptionBudget {
  /**
   * @schema ExternalSecretsPodDisruptionBudget#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsPodDisruptionBudget#minAvailable
   */
  readonly minAvailable?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsPodDisruptionBudget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsPodLabels
 */
export interface ExternalSecretsPodLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsPodLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsPodSecurityContext
 */
export interface ExternalSecretsPodSecurityContext {
  /**
   * @schema ExternalSecretsPodSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsPodSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsPodSpecExtra
 */
export interface ExternalSecretsPodSpecExtra {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsPodSpecExtra#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsRbac
 */
export interface ExternalSecretsRbac {
  /**
   * @schema ExternalSecretsRbac#aggregateToEdit
   */
  readonly aggregateToEdit?: boolean;

  /**
   * @schema ExternalSecretsRbac#aggregateToView
   */
  readonly aggregateToView?: boolean;

  /**
   * @schema ExternalSecretsRbac#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsRbac#servicebindings
   */
  readonly servicebindings?: ExternalSecretsRbacServicebindings;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsResources
 */
export interface ExternalSecretsResources {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsResources#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsSecurityContext
 */
export interface ExternalSecretsSecurityContext {
  /**
   * @schema ExternalSecretsSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * @schema ExternalSecretsSecurityContext#capabilities
   */
  readonly capabilities?: ExternalSecretsSecurityContextCapabilities;

  /**
   * @schema ExternalSecretsSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * @schema ExternalSecretsSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * @schema ExternalSecretsSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * @schema ExternalSecretsSecurityContext#seccompProfile
   */
  readonly seccompProfile?: ExternalSecretsSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsService
 */
export interface ExternalSecretsService {
  /**
   * @schema ExternalSecretsService#ipFamilies
   */
  readonly ipFamilies?: any[];

  /**
   * @schema ExternalSecretsService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsServiceAccount
 */
export interface ExternalSecretsServiceAccount {
  /**
   * @schema ExternalSecretsServiceAccount#annotations
   */
  readonly annotations?: ExternalSecretsServiceAccountAnnotations;

  /**
   * @schema ExternalSecretsServiceAccount#automount
   */
  readonly automount?: boolean;

  /**
   * @schema ExternalSecretsServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsServiceAccount#extraLabels
   */
  readonly extraLabels?: ExternalSecretsServiceAccountExtraLabels;

  /**
   * @schema ExternalSecretsServiceAccount#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsServiceMonitor
 */
export interface ExternalSecretsServiceMonitor {
  /**
   * @schema ExternalSecretsServiceMonitor#additionalLabels
   */
  readonly additionalLabels?: ExternalSecretsServiceMonitorAdditionalLabels;

  /**
   * @schema ExternalSecretsServiceMonitor#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsServiceMonitor#honorLabels
   */
  readonly honorLabels?: boolean;

  /**
   * @schema ExternalSecretsServiceMonitor#interval
   */
  readonly interval?: string;

  /**
   * @schema ExternalSecretsServiceMonitor#metricRelabelings
   */
  readonly metricRelabelings?: any[];

  /**
   * @schema ExternalSecretsServiceMonitor#namespace
   */
  readonly namespace?: string;

  /**
   * @schema ExternalSecretsServiceMonitor#relabelings
   */
  readonly relabelings?: any[];

  /**
   * @schema ExternalSecretsServiceMonitor#scrapeTimeout
   */
  readonly scrapeTimeout?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsServiceMonitor#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhook
 */
export interface ExternalSecretsWebhook {
  /**
   * @schema ExternalSecretsWebhook#affinity
   */
  readonly affinity?: ExternalSecretsWebhookAffinity;

  /**
   * @schema ExternalSecretsWebhook#annotations
   */
  readonly annotations?: ExternalSecretsWebhookAnnotations;

  /**
   * @schema ExternalSecretsWebhook#certCheckInterval
   */
  readonly certCheckInterval?: string;

  /**
   * @schema ExternalSecretsWebhook#certDir
   */
  readonly certDir?: string;

  /**
   * @schema ExternalSecretsWebhook#certManager
   */
  readonly certManager?: ExternalSecretsWebhookCertManager;

  /**
   * @schema ExternalSecretsWebhook#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsWebhook#deploymentAnnotations
   */
  readonly deploymentAnnotations?: ExternalSecretsWebhookDeploymentAnnotations;

  /**
   * @schema ExternalSecretsWebhook#extraArgs
   */
  readonly extraArgs?: ExternalSecretsWebhookExtraArgs;

  /**
   * @schema ExternalSecretsWebhook#extraEnv
   */
  readonly extraEnv?: any[];

  /**
   * @schema ExternalSecretsWebhook#extraVolumeMounts
   */
  readonly extraVolumeMounts?: any[];

  /**
   * @schema ExternalSecretsWebhook#extraVolumes
   */
  readonly extraVolumes?: any[];

  /**
   * @schema ExternalSecretsWebhook#failurePolicy
   */
  readonly failurePolicy?: string;

  /**
   * @schema ExternalSecretsWebhook#fullnameOverride
   */
  readonly fullnameOverride?: string;

  /**
   * @schema ExternalSecretsWebhook#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * @schema ExternalSecretsWebhook#image
   */
  readonly image?: ExternalSecretsWebhookImage;

  /**
   * @schema ExternalSecretsWebhook#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * @schema ExternalSecretsWebhook#log
   */
  readonly log?: ExternalSecretsWebhookLog;

  /**
   * @schema ExternalSecretsWebhook#lookaheadInterval
   */
  readonly lookaheadInterval?: string;

  /**
   * @schema ExternalSecretsWebhook#metrics
   */
  readonly metrics?: ExternalSecretsWebhookMetrics;

  /**
   * @schema ExternalSecretsWebhook#nameOverride
   */
  readonly nameOverride?: string;

  /**
   * @schema ExternalSecretsWebhook#nodeSelector
   */
  readonly nodeSelector?: ExternalSecretsWebhookNodeSelector;

  /**
   * @schema ExternalSecretsWebhook#podAnnotations
   */
  readonly podAnnotations?: ExternalSecretsWebhookPodAnnotations;

  /**
   * @schema ExternalSecretsWebhook#podDisruptionBudget
   */
  readonly podDisruptionBudget?: ExternalSecretsWebhookPodDisruptionBudget;

  /**
   * @schema ExternalSecretsWebhook#podLabels
   */
  readonly podLabels?: ExternalSecretsWebhookPodLabels;

  /**
   * @schema ExternalSecretsWebhook#podSecurityContext
   */
  readonly podSecurityContext?: ExternalSecretsWebhookPodSecurityContext;

  /**
   * @schema ExternalSecretsWebhook#port
   */
  readonly port?: number;

  /**
   * @schema ExternalSecretsWebhook#priorityClassName
   */
  readonly priorityClassName?: string;

  /**
   * @schema ExternalSecretsWebhook#rbac
   */
  readonly rbac?: ExternalSecretsWebhookRbac;

  /**
   * @schema ExternalSecretsWebhook#readinessProbe
   */
  readonly readinessProbe?: ExternalSecretsWebhookReadinessProbe;

  /**
   * @schema ExternalSecretsWebhook#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * @schema ExternalSecretsWebhook#resources
   */
  readonly resources?: ExternalSecretsWebhookResources;

  /**
   * @schema ExternalSecretsWebhook#revisionHistoryLimit
   */
  readonly revisionHistoryLimit?: number;

  /**
   * @schema ExternalSecretsWebhook#secretAnnotations
   */
  readonly secretAnnotations?: ExternalSecretsWebhookSecretAnnotations;

  /**
   * @schema ExternalSecretsWebhook#securityContext
   */
  readonly securityContext?: ExternalSecretsWebhookSecurityContext;

  /**
   * @schema ExternalSecretsWebhook#service
   */
  readonly service?: ExternalSecretsWebhookService;

  /**
   * @schema ExternalSecretsWebhook#serviceAccount
   */
  readonly serviceAccount?: ExternalSecretsWebhookServiceAccount;

  /**
   * @schema ExternalSecretsWebhook#tolerations
   */
  readonly tolerations?: any[];

  /**
   * @schema ExternalSecretsWebhook#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhook#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerAffinity
 */
export interface ExternalSecretsCertControllerAffinity {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerAffinity#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerDeploymentAnnotations
 */
export interface ExternalSecretsCertControllerDeploymentAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerDeploymentAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerExtraArgs
 */
export interface ExternalSecretsCertControllerExtraArgs {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerExtraArgs#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerImage
 */
export interface ExternalSecretsCertControllerImage {
  /**
   * @schema ExternalSecretsCertControllerImage#flavour
   */
  readonly flavour?: string;

  /**
   * @schema ExternalSecretsCertControllerImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema ExternalSecretsCertControllerImage#repository
   */
  readonly repository?: string;

  /**
   * @schema ExternalSecretsCertControllerImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerLog
 */
export interface ExternalSecretsCertControllerLog {
  /**
   * @schema ExternalSecretsCertControllerLog#level
   */
  readonly level?: string;

  /**
   * @schema ExternalSecretsCertControllerLog#timeEncoding
   */
  readonly timeEncoding?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerLog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerMetrics
 */
export interface ExternalSecretsCertControllerMetrics {
  /**
   * @schema ExternalSecretsCertControllerMetrics#listen
   */
  readonly listen?: ExternalSecretsCertControllerMetricsListen;

  /**
   * @schema ExternalSecretsCertControllerMetrics#service
   */
  readonly service?: ExternalSecretsCertControllerMetricsService;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerNodeSelector
 */
export interface ExternalSecretsCertControllerNodeSelector {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerNodeSelector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerPodAnnotations
 */
export interface ExternalSecretsCertControllerPodAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerPodAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerPodDisruptionBudget
 */
export interface ExternalSecretsCertControllerPodDisruptionBudget {
  /**
   * @schema ExternalSecretsCertControllerPodDisruptionBudget#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsCertControllerPodDisruptionBudget#minAvailable
   */
  readonly minAvailable?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerPodDisruptionBudget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerPodLabels
 */
export interface ExternalSecretsCertControllerPodLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerPodLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerPodSecurityContext
 */
export interface ExternalSecretsCertControllerPodSecurityContext {
  /**
   * @schema ExternalSecretsCertControllerPodSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerPodSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerRbac
 */
export interface ExternalSecretsCertControllerRbac {
  /**
   * @schema ExternalSecretsCertControllerRbac#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerReadinessProbe
 */
export interface ExternalSecretsCertControllerReadinessProbe {
  /**
   * @schema ExternalSecretsCertControllerReadinessProbe#address
   */
  readonly address?: string;

  /**
   * @schema ExternalSecretsCertControllerReadinessProbe#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerResources
 */
export interface ExternalSecretsCertControllerResources {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerResources#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerSecurityContext
 */
export interface ExternalSecretsCertControllerSecurityContext {
  /**
   * @schema ExternalSecretsCertControllerSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#capabilities
   */
  readonly capabilities?: ExternalSecretsCertControllerSecurityContextCapabilities;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * @schema ExternalSecretsCertControllerSecurityContext#seccompProfile
   */
  readonly seccompProfile?: ExternalSecretsCertControllerSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerServiceAccount
 */
export interface ExternalSecretsCertControllerServiceAccount {
  /**
   * @schema ExternalSecretsCertControllerServiceAccount#annotations
   */
  readonly annotations?: ExternalSecretsCertControllerServiceAccountAnnotations;

  /**
   * @schema ExternalSecretsCertControllerServiceAccount#automount
   */
  readonly automount?: boolean;

  /**
   * @schema ExternalSecretsCertControllerServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsCertControllerServiceAccount#extraLabels
   */
  readonly extraLabels?: ExternalSecretsCertControllerServiceAccountExtraLabels;

  /**
   * @schema ExternalSecretsCertControllerServiceAccount#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCrdsAnnotations
 */
export interface ExternalSecretsCrdsAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCrdsAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCrdsConversion
 */
export interface ExternalSecretsCrdsConversion {
  /**
   * @schema ExternalSecretsCrdsConversion#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCrdsConversion#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsGrafanaDashboardAnnotations
 */
export interface ExternalSecretsGrafanaDashboardAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsGrafanaDashboardAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsMetricsListen
 */
export interface ExternalSecretsMetricsListen {
  /**
   * @schema ExternalSecretsMetricsListen#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsMetricsListen#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsMetricsService
 */
export interface ExternalSecretsMetricsService {
  /**
   * @schema ExternalSecretsMetricsService#annotations
   */
  readonly annotations?: ExternalSecretsMetricsServiceAnnotations;

  /**
   * @schema ExternalSecretsMetricsService#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsMetricsService#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsMetricsService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsRbacServicebindings
 */
export interface ExternalSecretsRbacServicebindings {
  /**
   * @schema ExternalSecretsRbacServicebindings#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsRbacServicebindings#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsSecurityContextCapabilities
 */
export interface ExternalSecretsSecurityContextCapabilities {
  /**
   * @schema ExternalSecretsSecurityContextCapabilities#drop
   */
  readonly drop?: string[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsSecurityContextCapabilities#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsSecurityContextSeccompProfile
 */
export interface ExternalSecretsSecurityContextSeccompProfile {
  /**
   * @schema ExternalSecretsSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsServiceAccountAnnotations
 */
export interface ExternalSecretsServiceAccountAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsServiceAccountAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsServiceAccountExtraLabels
 */
export interface ExternalSecretsServiceAccountExtraLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsServiceAccountExtraLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsServiceMonitorAdditionalLabels
 */
export interface ExternalSecretsServiceMonitorAdditionalLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsServiceMonitorAdditionalLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookAffinity
 */
export interface ExternalSecretsWebhookAffinity {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookAffinity#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookAnnotations
 */
export interface ExternalSecretsWebhookAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookCertManager
 */
export interface ExternalSecretsWebhookCertManager {
  /**
   * @schema ExternalSecretsWebhookCertManager#addInjectorAnnotations
   */
  readonly addInjectorAnnotations?: boolean;

  /**
   * @schema ExternalSecretsWebhookCertManager#cert
   */
  readonly cert?: ExternalSecretsWebhookCertManagerCert;

  /**
   * @schema ExternalSecretsWebhookCertManager#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookCertManager#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookDeploymentAnnotations
 */
export interface ExternalSecretsWebhookDeploymentAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookDeploymentAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookExtraArgs
 */
export interface ExternalSecretsWebhookExtraArgs {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookExtraArgs#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookImage
 */
export interface ExternalSecretsWebhookImage {
  /**
   * @schema ExternalSecretsWebhookImage#flavour
   */
  readonly flavour?: string;

  /**
   * @schema ExternalSecretsWebhookImage#pullPolicy
   */
  readonly pullPolicy?: string;

  /**
   * @schema ExternalSecretsWebhookImage#repository
   */
  readonly repository?: string;

  /**
   * @schema ExternalSecretsWebhookImage#tag
   */
  readonly tag?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookImage#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookLog
 */
export interface ExternalSecretsWebhookLog {
  /**
   * @schema ExternalSecretsWebhookLog#level
   */
  readonly level?: string;

  /**
   * @schema ExternalSecretsWebhookLog#timeEncoding
   */
  readonly timeEncoding?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookLog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookMetrics
 */
export interface ExternalSecretsWebhookMetrics {
  /**
   * @schema ExternalSecretsWebhookMetrics#listen
   */
  readonly listen?: ExternalSecretsWebhookMetricsListen;

  /**
   * @schema ExternalSecretsWebhookMetrics#service
   */
  readonly service?: ExternalSecretsWebhookMetricsService;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookNodeSelector
 */
export interface ExternalSecretsWebhookNodeSelector {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookNodeSelector#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookPodAnnotations
 */
export interface ExternalSecretsWebhookPodAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookPodAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookPodDisruptionBudget
 */
export interface ExternalSecretsWebhookPodDisruptionBudget {
  /**
   * @schema ExternalSecretsWebhookPodDisruptionBudget#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsWebhookPodDisruptionBudget#minAvailable
   */
  readonly minAvailable?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookPodDisruptionBudget#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookPodLabels
 */
export interface ExternalSecretsWebhookPodLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookPodLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookPodSecurityContext
 */
export interface ExternalSecretsWebhookPodSecurityContext {
  /**
   * @schema ExternalSecretsWebhookPodSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookPodSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookRbac
 */
export interface ExternalSecretsWebhookRbac {
  /**
   * @schema ExternalSecretsWebhookRbac#create
   */
  readonly create?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookRbac#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookReadinessProbe
 */
export interface ExternalSecretsWebhookReadinessProbe {
  /**
   * @schema ExternalSecretsWebhookReadinessProbe#address
   */
  readonly address?: string;

  /**
   * @schema ExternalSecretsWebhookReadinessProbe#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookReadinessProbe#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookResources
 */
export interface ExternalSecretsWebhookResources {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookResources#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookSecretAnnotations
 */
export interface ExternalSecretsWebhookSecretAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookSecretAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookSecurityContext
 */
export interface ExternalSecretsWebhookSecurityContext {
  /**
   * @schema ExternalSecretsWebhookSecurityContext#allowPrivilegeEscalation
   */
  readonly allowPrivilegeEscalation?: boolean;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#capabilities
   */
  readonly capabilities?: ExternalSecretsWebhookSecurityContextCapabilities;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#readOnlyRootFilesystem
   */
  readonly readOnlyRootFilesystem?: boolean;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#runAsNonRoot
   */
  readonly runAsNonRoot?: boolean;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#runAsUser
   */
  readonly runAsUser?: number;

  /**
   * @schema ExternalSecretsWebhookSecurityContext#seccompProfile
   */
  readonly seccompProfile?: ExternalSecretsWebhookSecurityContextSeccompProfile;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookSecurityContext#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookService
 */
export interface ExternalSecretsWebhookService {
  /**
   * @schema ExternalSecretsWebhookService#annotations
   */
  readonly annotations?: ExternalSecretsWebhookServiceAnnotations;

  /**
   * @schema ExternalSecretsWebhookService#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsWebhookService#labels
   */
  readonly labels?: ExternalSecretsWebhookServiceLabels;

  /**
   * @schema ExternalSecretsWebhookService#loadBalancerIP
   */
  readonly loadBalancerIp?: string;

  /**
   * @schema ExternalSecretsWebhookService#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookServiceAccount
 */
export interface ExternalSecretsWebhookServiceAccount {
  /**
   * @schema ExternalSecretsWebhookServiceAccount#annotations
   */
  readonly annotations?: ExternalSecretsWebhookServiceAccountAnnotations;

  /**
   * @schema ExternalSecretsWebhookServiceAccount#automount
   */
  readonly automount?: boolean;

  /**
   * @schema ExternalSecretsWebhookServiceAccount#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsWebhookServiceAccount#extraLabels
   */
  readonly extraLabels?: ExternalSecretsWebhookServiceAccountExtraLabels;

  /**
   * @schema ExternalSecretsWebhookServiceAccount#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookServiceAccount#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerMetricsListen
 */
export interface ExternalSecretsCertControllerMetricsListen {
  /**
   * @schema ExternalSecretsCertControllerMetricsListen#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerMetricsListen#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerMetricsService
 */
export interface ExternalSecretsCertControllerMetricsService {
  /**
   * @schema ExternalSecretsCertControllerMetricsService#annotations
   */
  readonly annotations?: ExternalSecretsCertControllerMetricsServiceAnnotations;

  /**
   * @schema ExternalSecretsCertControllerMetricsService#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsCertControllerMetricsService#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerMetricsService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerSecurityContextCapabilities
 */
export interface ExternalSecretsCertControllerSecurityContextCapabilities {
  /**
   * @schema ExternalSecretsCertControllerSecurityContextCapabilities#drop
   */
  readonly drop?: string[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerSecurityContextCapabilities#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerSecurityContextSeccompProfile
 */
export interface ExternalSecretsCertControllerSecurityContextSeccompProfile {
  /**
   * @schema ExternalSecretsCertControllerSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerServiceAccountAnnotations
 */
export interface ExternalSecretsCertControllerServiceAccountAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerServiceAccountAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerServiceAccountExtraLabels
 */
export interface ExternalSecretsCertControllerServiceAccountExtraLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerServiceAccountExtraLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsMetricsServiceAnnotations
 */
export interface ExternalSecretsMetricsServiceAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsMetricsServiceAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookCertManagerCert
 */
export interface ExternalSecretsWebhookCertManagerCert {
  /**
   * @schema ExternalSecretsWebhookCertManagerCert#annotations
   */
  readonly annotations?: ExternalSecretsWebhookCertManagerCertAnnotations;

  /**
   * @schema ExternalSecretsWebhookCertManagerCert#create
   */
  readonly create?: boolean;

  /**
   * @schema ExternalSecretsWebhookCertManagerCert#duration
   */
  readonly duration?: string;

  /**
   * @schema ExternalSecretsWebhookCertManagerCert#issuerRef
   */
  readonly issuerRef?: ExternalSecretsWebhookCertManagerCertIssuerRef;

  /**
   * @schema ExternalSecretsWebhookCertManagerCert#renewBefore
   */
  readonly renewBefore?: string;

  /**
   * @schema ExternalSecretsWebhookCertManagerCert#revisionHistoryLimit
   */
  readonly revisionHistoryLimit?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookCertManagerCert#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookMetricsListen
 */
export interface ExternalSecretsWebhookMetricsListen {
  /**
   * @schema ExternalSecretsWebhookMetricsListen#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookMetricsListen#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookMetricsService
 */
export interface ExternalSecretsWebhookMetricsService {
  /**
   * @schema ExternalSecretsWebhookMetricsService#annotations
   */
  readonly annotations?: ExternalSecretsWebhookMetricsServiceAnnotations;

  /**
   * @schema ExternalSecretsWebhookMetricsService#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema ExternalSecretsWebhookMetricsService#port
   */
  readonly port?: number;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookMetricsService#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookSecurityContextCapabilities
 */
export interface ExternalSecretsWebhookSecurityContextCapabilities {
  /**
   * @schema ExternalSecretsWebhookSecurityContextCapabilities#drop
   */
  readonly drop?: string[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookSecurityContextCapabilities#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookSecurityContextSeccompProfile
 */
export interface ExternalSecretsWebhookSecurityContextSeccompProfile {
  /**
   * @schema ExternalSecretsWebhookSecurityContextSeccompProfile#type
   */
  readonly type?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookSecurityContextSeccompProfile#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookServiceAnnotations
 */
export interface ExternalSecretsWebhookServiceAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookServiceAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookServiceLabels
 */
export interface ExternalSecretsWebhookServiceLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookServiceLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookServiceAccountAnnotations
 */
export interface ExternalSecretsWebhookServiceAccountAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookServiceAccountAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookServiceAccountExtraLabels
 */
export interface ExternalSecretsWebhookServiceAccountExtraLabels {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookServiceAccountExtraLabels#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsCertControllerMetricsServiceAnnotations
 */
export interface ExternalSecretsCertControllerMetricsServiceAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsCertControllerMetricsServiceAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookCertManagerCertAnnotations
 */
export interface ExternalSecretsWebhookCertManagerCertAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookCertManagerCertAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookCertManagerCertIssuerRef
 */
export interface ExternalSecretsWebhookCertManagerCertIssuerRef {
  /**
   * @schema ExternalSecretsWebhookCertManagerCertIssuerRef#group
   */
  readonly group?: string;

  /**
   * @schema ExternalSecretsWebhookCertManagerCertIssuerRef#kind
   */
  readonly kind?: string;

  /**
   * @schema ExternalSecretsWebhookCertManagerCertIssuerRef#name
   */
  readonly name?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookCertManagerCertIssuerRef#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

/**
 * @schema ExternalSecretsWebhookMetricsServiceAnnotations
 */
export interface ExternalSecretsWebhookMetricsServiceAnnotations {
  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ExternalSecretsWebhookMetricsServiceAnnotations#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };

}

