apiVersion: batch/v1
kind: Job
metadata:
  name: test-webhook-setup
  namespace: kargo-pipelines
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: webhook-test
        image: curlimages/curl:8.5.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -x
          echo "Testing Gitea connectivity..."
          
          # Test basic connectivity
          curl -k -v https://gitea.cnoe.localtest.me:8443/api/v1/version 2>&1 | head -20
          
          echo ""
          echo "Testing with API token..."
          API_TOKEN="808ee2f2ddf7b277f1a539f310b8ef4b8ee18612"
          
          # Test API with token
          curl -k -s -X GET \
            "https://gitea.cnoe.localtest.me:8443/api/v1/admin/hooks" \
            -H "Authorization: token $API_TOKEN" 2>&1