kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
    # Mount the entire keys directory instead of individual files
    - hostPath: /home/vscode/workspace/stacks/ref-implementation/keys
      containerPath: /etc/kubernetes/pki/custom-keys
      readOnly: true
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        service-account-issuer: "https://oidcissuer65846b7df97b.z13.web.core.windows.net/"
        service-account-key-file: /etc/kubernetes/pki/custom-keys/sa.pub
        service-account-signing-key-file: /etc/kubernetes/pki/custom-keys/sa.key
    controllerManager:
      extraArgs:
        service-account-private-key-file: /etc/kubernetes/pki/custom-keys/sa.key
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP