kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # Use the Docker default bridge network
  ipFamily: ipv4
  apiServerAddress: "0.0.0.0"
  apiServerPort: 6443
nodes:
- role: control-plane
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 6443
    hostPort: 6443
    protocol: TCP