apiVersion: v1
kind: Pod
metadata:
  name: wi-test-pod
  namespace: external-secrets
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: external-secrets
  containers:
  - name: test-container
    image: mcr.microsoft.com/azure-cli:latest
    command: ["/bin/bash", "-c"]
    args:
    - |
      echo "=== Azure Workload Identity Test ==="
      echo ""
      echo "1. Checking injected environment variables:"
      env | grep -E '^AZURE_' || echo "No AZURE_ variables found"
      echo ""
      echo "2. Testing Azure authentication:"
      if [ -n "$AZURE_FEDERATED_TOKEN_FILE" ] && [ -n "$AZURE_CLIENT_ID" ] && [ -n "$AZURE_TENANT_ID" ]; then
        echo "Attempting Azure login with federated token..."
        az login --federated-token "$(cat $AZURE_FEDERATED_TOKEN_FILE)" \
          --service-principal -u $AZURE_CLIENT_ID -t $AZURE_TENANT_ID \
          && echo "SUCCESS: Authentication successful!" \
          || echo "FAILED: Authentication failed"
      else
        echo "ERROR: Missing required environment variables for authentication"
      fi
      echo ""
      echo "Test complete. Pod will exit."
  nodeSelector:
    kubernetes.io/os: linux