offline: local
policy: cdk8s
customPolicies:
  - name: cdk8s
    isDefault: true
    rules:
      - identifier: CONTAINERS_MISSING_MEMORY_REQUEST_LIMIT
        messageOnFailure: Container is missing memory request and limit
      - identifier: CONTAINERS_MISSING_CPU_REQUEST_LIMIT
        messageOnFailure: Container is missing CPU request and limit
      - identifier: CONTAINERS_MISSING_LIVENESSPROBE
        messageOnFailure: Container is missing liveness probe
      - identifier: CONTAINERS_MISSING_READINESSPROBE
        messageOnFailure: Container is missing readiness probe
      - identifier: CONTAINERS_IMAGE_TAG_MISSING
        messageOnFailure: Container image tag is missing or latest
      - identifier: INGRESS_INCORRECT_HOST
        messageOnFailure: Ingress host is not a valid domain
      - identifier: SERVICE_MISSING_SELECTOR
        messageOnFailure: Service is missing selector
      - identifier: DEPLOYMENT_MISSING_REPLICAS
        messageOnFailure: Deployment is missing replicas
      - identifier: WORKLOAD_MISSING_SECURITY_CONTEXT
        messageOnFailure: Workload is missing security context
      - identifier: CONTAINERS_MISSING_SECURITY_CONTEXT
        messageOnFailure: Container is missing security context